# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Guia Comum Do Recife' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Guia Comum Do Recife

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  target 'Guia Comum Do RecifeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Guia Comum Do RecifeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
